name: dynasty_urban_style
description: The Admin dasboard of the dynasty urban style web app for shop, user and transaction management and review

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Flutter
  cupertino_icons: ^1.0.2

  # State Management
  get: ^4.6.1

  # Charts
  data_table_2: ^2.2.0
  charts_flutter: ^0.12.0

  # Ecosystem
  path_provider: ^2.0.8
  shimmer: ^2.0.0

  # Fonts
  google_fonts: ^2.2.0

  # Animation
  lottie: ^1.2.1
  animations: ^2.0.2

  # Images
  flutter_svg: ^1.0.3
  url_launcher: ^6.0.18

  # API
  dio: ^4.0.4
  graphql_flutter: ^5.0.0

  # Connectivity
  connectivity_plus: ^2.2.0
  internet_connection_checker: ^0.0.1+3

  # Utils
  intl: ^0.17.0
  auto_size_text: ^3.0.0
  badges: ^2.0.2

  # Widgets
  qr_flutter: ^4.0.0
  material_floating_search_bar: ^0.3.6
  carousel_slider: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Flutter Lints
  flutter_lints: ^1.0.0

  # launcher Icons
  flutter_launcher_icons: ^0.9.2

  # Native Splash
  flutter_native_splash: ^2.0.1+1

flutter_icons:
  image_path_android: "assets/images/core/icon.png"
  image_path_ios: "assets/images/core/icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "#000000"

flutter_native_splash:
  background_image: "assets/images/welcome/splash_light.png"
  background_image_dark: "assets/images/welcome/splash_dark.png"
  android: true
  ios: true
  android_gravity: fill
  ios_content_mode: scaleAspectFill

flutter:
  uses-material-design: true

  assets:
    - assets/images/app/language/
    - assets/images/app/screen/
    - assets/images/core/
    - assets/images/core/dialog_widget_icons/
    - assets/icons/
